// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PodsColumns holds the columns for the "pods" table.
	PodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString},
	}
	// PodsTable holds the schema information for the "pods" table.
	PodsTable = &schema.Table{
		Name:       "pods",
		Columns:    PodsColumns,
		PrimaryKey: []*schema.Column{PodsColumns[0]},
	}
	// ResourcesColumns holds the columns for the "resources" table.
	ResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "node_name", Type: field.TypeString},
	}
	// ResourcesTable holds the schema information for the "resources" table.
	ResourcesTable = &schema.Table{
		Name:       "resources",
		Columns:    ResourcesColumns,
		PrimaryKey: []*schema.Column{ResourcesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "resource_node_name",
				Unique:  true,
				Columns: []*schema.Column{ResourcesColumns[2]},
			},
		},
	}
	// PodResourceColumns holds the columns for the "pod_resource" table.
	PodResourceColumns = []*schema.Column{
		{Name: "pod_id", Type: field.TypeUUID},
		{Name: "resource_id", Type: field.TypeUUID},
	}
	// PodResourceTable holds the schema information for the "pod_resource" table.
	PodResourceTable = &schema.Table{
		Name:       "pod_resource",
		Columns:    PodResourceColumns,
		PrimaryKey: []*schema.Column{PodResourceColumns[0], PodResourceColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pod_resource_pod_id",
				Columns:    []*schema.Column{PodResourceColumns[0]},
				RefColumns: []*schema.Column{PodsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "pod_resource_resource_id",
				Columns:    []*schema.Column{PodResourceColumns[1]},
				RefColumns: []*schema.Column{ResourcesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PodsTable,
		ResourcesTable,
		PodResourceTable,
	}
)

func init() {
	PodResourceTable.ForeignKeys[0].RefTable = PodsTable
	PodResourceTable.ForeignKeys[1].RefTable = ResourcesTable
}
