apiVersion: v1
kind: Service
metadata:
  name: fastpod-controller-manager-svc
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 10086
      targetPort: 10086

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: fastpod-controller-manager-svc
  namespace: kube-system
  labels:
    kubernetes.io/service-name: fastpod-controller-manager-svc
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 10086
endpoints:
  - addresses:
      - "172.24.65.11"
