apiVersion: v1
kind: Service
metadata:
  name: fastpod-controller-manager-svc
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 10086
      targetPort: 10086

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: fastpod-controller-manager-svc
  namespace:
    kube-system
    # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: fastpod-controller-manager-svc
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 10086
endpoints:
  - addresses:
      - "192.168.128.88"
