apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-mps-server-daemonset
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "nvidia-mps"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nvidia-mps"
      name: "nvidia-mps"
    spec:
      restartPolicy: Always
      hostIPC: true
      initContainers:
        - name: set-compute-mode
          image: nvidia/cuda:12.2.2-base-ubuntu22.04
          command: ['nvidia-smi', '-c', 'EXCLUSIVE_PROCESS']
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      containers:
        - name: mps
          image: nvidia/mps
          volumeMounts:
            - name: nvidia-mps
              mountPath: /fastpod/mps
          env:
            - name: NVIDIA_REQUIRE_VOLTA
              value: "arch>=5.0"
            - name: CUDA_MPS_PIPE_DIRECTORY
              value: /fastpod/mps/tmp
            - name: CUDA_MPS_LOG_DIRECTORY
              value: /fastpod/mps/log
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      volumes:
        - name: nvidia-mps
          hostPath:
            path: /fastpod/mps

    