apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-fastpod
  namespace: fast-gshare-fn
  labels:
    com.openfaas.scale.min: "1"
    com.openfaas.scale.max: "3"
  annotations:
    fastgshare/gpu_quota_request: "0.7"
    fastgshare/gpu_quota_limit: "0.8"
    fastgshare/gpu_sm_partition: "20"
    fastgshare/gpu_mem: "100000000"
    fastgshare/allocation_type: "FASTPOD"
    fastgshare/node_name: "kgpu1"
    fastgshare/vgpu_uuid: "GPU-5b6ec351-6067-def5-6148-17bbe9ac6a64"
spec:
  replicas: 1
  podSpec:
    containers:
    - name: resnet-pytorch
      image: docker.io/kontonpuku666/mlperf-resnet:pytorch
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 10
      # env:
      #   - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
      #     value: "60"
      # ports:
      # - containerPort: 5000
      #   hostPort: 5000
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
      # command: ["/bin/bash", "-c"]
      # args: ["sleep 7200"]
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"
  
  
    
