apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-whisper
  namespace: fast-gshare-fn
  annotations: 
    fastgshare/gpu_quota_request: "1.0"
    fastgshare/gpu_quota_limit: "1.0"
    fastgshare/gpu_sm_partition: "52"
    fastgshare/gpu_mem: "1073741824"
    fastgshare/allocation_type: "FASTPOD"
    fastgshare/node_name: "atschulz7"
    fastgshare/vgpu_uuid: "GPU-5b6ec351-6067-def5-6148-17bbe9ac6a64"
spec:
  replicas: 1
  podSpec:
    containers:
    - name: whisper-pytorch
      image: ishworgiri/whisper
      imagePullPolicy: Always
      # env:
      #   - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
      #     value: "60"
      
      ports:
      - containerPort: 5000
        # hostPort: 5000
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"
  
  
    
