apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-fastpod-phi
  namespace: fast-gshare
  annotations:
    fastgshare/gpu_quota_request: "0.5"
    fastgshare/gpu_quota_limit: "0.5"
    fastgshare/gpu_sm_partition: "50"
    fastgshare/gpu_mem: "6294967296"
spec:
  replicas: 1
  podSpec:
    containers:
      - name: phi3-mini-4k
        image: ishworgiri/phi3-mini-onnxruntime
        imagePullPolicy: Always #IfNotPresent
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: "model-volume"
            mountPath: "/models/"
    volumes:
      - name: "model-volume"
        hostPath:
          path: "/models/"
