apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-fastpod-2
  namespace: fast-gshare
  annotations:
    fastgshare/gpu_quota_request: "0.7"
    fastgshare/gpu_quota_limit: "0.8"
    fastgshare/gpu_sm_partition: "50"
    fastgshare/gpu_mem: "2700000000"
spec:
  replicas: 1
  podSpec:
    containers:
      - name: gnmt
        image: yukiozhu/mlperf-faas-bert #ishworgiri/resnet-flask:cuda11.3 #ishworgiri/mlperf-faas-resnet:pytorch
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - /workspace/probe/probe.sh
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        startupProbe:
          exec:
            command:
              - /bin/bash
              - /workspace/probe/probe.sh
          failureThreshold: 30
          periodSeconds: 2
        ports:
          - containerPort: 5000
            hostPort: 5000
        volumeMounts:
          - name: "model-volume"
            mountPath: "/models/"
        volumes:
          - name: "model-volume"
            hostPath:
              path: "/models/"
