apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-bert
  namespace: fast-gshare-fn
  annotations: 
    fastgshare/gpu_quota_request: "1.0"
    fastgshare/gpu_quota_limit: "1.0"
    fastgshare/gpu_sm_partition: "20"
    fastgshare/gpu_mem: "2147483648"
    fastgshare/allocation_type: "FASTPOD"
    fastgshare/node_name: "i10se14"
    fastgshare/vgpu_uuid: "GPU-c681a026-7f84-dafd-e970-6b191593230e"
spec:
  replicas: 5
  podSpec:
    containers:
    - name: bert-pytorch
      image: ishworgiri/bert:pytorch
      imagePullPolicy: IfNotPresent
      # env:
      #   - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
      #     value: "60"
      
      ports:
      - containerPort: 5000
        # hostPort: 5000
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"
  
  
    
