apiVersion: fastgshare.caps.in.tum/v1
kind: FaSTPod
metadata:
  name: test-whisper
  namespace: fast-gshare-fn
  annotations: 
    fastgshare/gpu_quota_request: "0.5"
    fastgshare/gpu_quota_limit: "0.5"
    fastgshare/gpu_sm_partition: "52"
    fastgshare/gpu_mem: "1073741824"
    fastgshare/allocation_type: "EXCLUSIVE"
    fastgshare/node_name: "atschulz7"
    fastgshare/vgpu_uuid: "MIG-d99e3a01-becd-5d26-82e0-35ace55b590c"
spec:
  replicas: 1
  podSpec:
    containers:
    - name: whisper-pytorch
      image: ishworgiri/whisper
      imagePullPolicy: IfNotPresent
      # env:
      #   - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
      #     value: "60"
      
      ports:
      - containerPort: 5000
        # hostPort: 5000
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"
  
  
    
