// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Pod is the predicate function for pod builders.
type Pod func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)
