// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/KontonGu/FaST-GShare/internal/db/ent/pod"
	"github.com/google/uuid"
)

// Pod is the model entity for the Pod schema.
type Pod struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Pod Name
	Name string `json:"name,omitempty"`
	// Resource ID
	ResourceID string `json:"resource_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PodQuery when eager-loading is set.
	Edges        PodEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PodEdges holds the relations/edges for other nodes in the graph.
type PodEdges struct {
	// Resource holds the value of the resource edge.
	Resource []*Resource `json:"resource,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResourceOrErr returns the Resource value or an error if the edge
// was not loaded in eager-loading.
func (e PodEdges) ResourceOrErr() ([]*Resource, error) {
	if e.loadedTypes[0] {
		return e.Resource, nil
	}
	return nil, &NotLoadedError{edge: "resource"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pod.FieldName, pod.FieldResourceID:
			values[i] = new(sql.NullString)
		case pod.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pod.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pod fields.
func (po *Pod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pod.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				po.ID = *value
			}
		case pod.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				po.CreatedAt = value.Time
			}
		case pod.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				po.Name = value.String
			}
		case pod.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				po.ResourceID = value.String
			}
		default:
			po.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pod.
// This includes values selected through modifiers, order, etc.
func (po *Pod) Value(name string) (ent.Value, error) {
	return po.selectValues.Get(name)
}

// QueryResource queries the "resource" edge of the Pod entity.
func (po *Pod) QueryResource() *ResourceQuery {
	return NewPodClient(po.config).QueryResource(po)
}

// Update returns a builder for updating this Pod.
// Note that you need to call Pod.Unwrap() before calling this method if this Pod
// was returned from a transaction, and the transaction was committed or rolled back.
func (po *Pod) Update() *PodUpdateOne {
	return NewPodClient(po.config).UpdateOne(po)
}

// Unwrap unwraps the Pod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (po *Pod) Unwrap() *Pod {
	_tx, ok := po.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pod is not a transactional entity")
	}
	po.config.driver = _tx.drv
	return po
}

// String implements the fmt.Stringer.
func (po *Pod) String() string {
	var builder strings.Builder
	builder.WriteString("Pod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", po.ID))
	builder.WriteString("created_at=")
	builder.WriteString(po.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(po.Name)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(po.ResourceID)
	builder.WriteByte(')')
	return builder.String()
}

// Pods is a parsable slice of Pod.
type Pods []*Pod
