// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/KontonGu/FaST-GShare/internal/db/ent/pod"
	"github.com/KontonGu/FaST-GShare/internal/db/ent/resource"
	"github.com/KontonGu/FaST-GShare/internal/db/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	podMixin := schema.Pod{}.Mixin()
	podMixinFields0 := podMixin[0].Fields()
	_ = podMixinFields0
	podFields := schema.Pod{}.Fields()
	_ = podFields
	// podDescCreatedAt is the schema descriptor for created_at field.
	podDescCreatedAt := podMixinFields0[0].Descriptor()
	// pod.DefaultCreatedAt holds the default value on creation for the created_at field.
	pod.DefaultCreatedAt = podDescCreatedAt.Default.(func() time.Time)
	// podDescID is the schema descriptor for id field.
	podDescID := podFields[0].Descriptor()
	// pod.DefaultID holds the default value on creation for the id field.
	pod.DefaultID = podDescID.Default.(func() uuid.UUID)
	resourceMixin := schema.Resource{}.Mixin()
	resourceMixinFields0 := resourceMixin[0].Fields()
	_ = resourceMixinFields0
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceMixinFields0[0].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescID is the schema descriptor for id field.
	resourceDescID := resourceFields[0].Descriptor()
	// resource.DefaultID holds the default value on creation for the id field.
	resource.DefaultID = resourceDescID.Default.(func() uuid.UUID)
}
